### ISSUE TITLE
Including html in several layout html files (like a footer for example)?

### ISSUE THREAD

**Issue by joerichsen** [under-os/under-os#4]
Is there any built-in way to include html snippets in the layout html files?

Ie. in order to have for example a shared header, footer, etc. on multiple pages.

**Comment by kaievns** [comment]
Hey Jørgen,

No, not really, at least not at the moment. Basically the train of thought goes like that

1) The layouts are supposed to be logic less, they just give you the idea how your page is structured
2) If you need a shared piece of logic aka widget, you supposed to write a custom `views/` class, for example, buttons, images, and more complicated components.
3) The pages are basically controllers and contain the higher level logic
4) CSS is for defining how things look like.

So, in your case, if it's just some static elements, i think you could get away with just an extra `<view class="header"></view>` in your layouts and defining common styles in the `application.css` file.

If it's more complicated element that has some behavior, then you need to build a component in the `views/` folder and then share it in your layouts.

Does it make sense?

**Comment by joerichsen** [comment]
Thank you for explaining your train of thought - it make's it lot easier to grasp the concepts :-)

I think that `<view class="header"></view>` will fit my use case quite nicely.

**Comment by kaievns** [comment]
no worries, let me know if you have any more questions :)
