### ISSUE TITLE
This is some potentially dangerous code

### ISSUE THREAD

**Issue by colinta** [under-os/under-os#9]
https://github.com/under-os/under-os/blob/master/ext/extconf.rb

If that `RUBYMOTION_TEMPLATES_DIR` constant is ever empty, that `rm -rf` command could potentially wipe the hard drive clean in very short order.  I'm not saying it's likely (`name` would have to be blank, too - and why would that happen?) but I think a sanity check before the `rm -rf` would not be a bad thing to have there.  Maybe make sure that RUBYMOTION_TEMPLATES_DIR and name aren't empty strings, something like that?

Just a thought! :smiley:

**Comment by kaievns** [comment]
good point. but i don't think File.expand_path will ever return an empty string

**Comment by colinta** [comment]
That's true, but a `/` would have the same effect (`rm -rf /// => rm -rf /)`.  I'm not as concerned with the code _as is_, but if this file were to ever change...

...well, I've said my peace, and it's your call.  I noticed this code and thought "wow that is really bold, to have that there with no sanity check".  It's unlikely to ever cause damage, but if it DID, it would be huge irreparable damage.

**Comment by kaievns** [comment]
yeah, that's true, i'll try to add some sanity checks

**Comment by colinta** [comment]
It wouldn't hurt, right? :smiley: :thumbsup:

**Comment by kaievns** [comment]
Hey Colin, sorry it took a while, been flatted out last few months :( but, i've added a RE in there address the issue. we should be all good now i think

**Comment by colinta** [comment]
awesome!

On Tue, Sep 23, 2014 at 4:51 PM, Nikolay Nemshilov <notifications@github.com
